
name: test
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure
        uses: rectalogic/notify-irc@v1
        if: github.event.pull_request.draft == false
        with:
          server: "irc.w3.org"
          port: 6679
          channel: "#infobot"
          nickname: gh-action-notifier
          tls: true
          message: |
            fail
