
name: Echidna
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: request to Echidna
        run: curl https://labs.w3.org/echidna/api/request --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
        env:
          URL: "https://w3c.github.io/manifest/ECHIDNA"
          DECISION: "https://www.w3.org/"
          TOKEN: "${{secrets.TOKEN}}"
